/**
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.ui.contentassist;

import br.ufes.inf.nemo.ontouml.ontoumlprime.ui.contentassist.AbstractDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
