/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DslUiModule extends br.ufes.inf.nemo.ontouml.ontoumlprime.ui.AbstractDslUiModule {
	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
