/**
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class DslQuickfixProvider extends DefaultQuickfixProvider {
}
