/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends br.ufes.inf.nemo.ontouml.ontoumlprime.AbstractDslRuntimeModule {

}
