/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends br.ufes.inf.nemo.ontouml.ontoumlprime.AbstractDslRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> 
	    bindIValueConverterService() {
	    return OntoUMLPrimeValueConverterService.class;
	}
	
}
