/*
* generated by Xtext
*/
package br.ufes.inf.nemo.ontouml.ontoumlprime;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return br.ufes.inf.nemo.ontouml.ontoumlprime.ui.internal.DslActivator.getInstance().getInjector("br.ufes.inf.nemo.ontouml.ontoumlprime.Dsl");
	}
	
}
