/**
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.validation;

import br.ufes.inf.nemo.ontouml.ontoumlprime.validation.AbstractDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
