/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://nemo.inf.ufes.br/ontouml/ontoumlprime"));
		return result;
	}
}
