/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import br.ufes.inf.nemo.ontouml.ontoumlprime.ui.internal.DslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DslActivator.getInstance().getInjector(DslActivator.BR_UFES_INF_NEMO_ONTOUML_ONTOUMLPRIME_DSL);
	}
	
}
