/*
* generated by Xtext
*/
package br.ufes.inf.nemo.ontouml.ontoumlprime.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("br/ufes/inf/nemo/ontouml/ontoumlprime/parser/antlr/internal/InternalDsl.tokens");
	}
}
