/**
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.serializer;

import br.ufes.inf.nemo.ontouml.ontoumlprime.serializer.AbstractDslSyntacticSequencer;

@SuppressWarnings("all")
public class DslSyntacticSequencer extends AbstractDslSyntacticSequencer {
}
