/**
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.ontoumlprime.serializer;

import br.ufes.inf.nemo.ontouml.ontoumlprime.serializer.AbstractDslSemanticSequencer;

@SuppressWarnings("all")
public class DslSemanticSequencer extends AbstractDslSemanticSequencer {
}
